apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "server-app"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ws.unlucoin.info
      secretName: ws-cert-tls1
    - hosts:
        - cd.unlucoin.info
      secretName: ws-cert-tls2
    - hosts:
        - pm.unlucoin.info
      secretName: ws-cert-tls3
  rules:
    - host: ws.unlucoin.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-app
                port:
                  number: 80
    - host: cd.unlucoin.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-coordinador
                port:
                  number: 8080
    - host: pm.unlucoin.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-poolmanager
                port:
                  number: 8080

